version: '2'
services:

  #BACKEND-BENEFICIOS
  burger:
    image: burger:latest
    container_name: burger-back
    hostname: localhost
    restart: always
    ports:
      - 8081:8081
      - 80:80
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf:rw
      - ./nome/:/etc/nome/:rw
